### ISSUE TITLE
Real Time Support

### ISSUE THREAD

**Issue by weedrater** [Canner/redux-firebase-middleware#2]
Hello,

This library looks very promising.  I'm curious to see if it provides support for Firebase's real time features.   Does it allow real time dispatching of actions based on updates made to the data in Firebase?

thanks

**Comment by chilijung** [comment]
yes your right, currently realtime feature is not supported. But I've planned to do it when I have time.  It would be nice if you PR this feature.

**Comment by chilijung** [comment]
This is support in the latest version, check out in Readme.
